export const DOCUMENT_TYPE_LABELS = {
  SALE_DEED: "Sale Deed",
  PARENT_DEED: "Previous Sale Deed / Parent Deed",
  ENCUMBRANCE_CERTIFICATE: "Encumbrance Certificate",
  KHATA_PROPERTY_REGISTER: "Khata / Property Register",
  MUTATION_REVENUE_RECORD: "Mutation / Revenue Record",
  COURT_CASE_DOCUMENT: "Court Case Document",
  COURT_ORDER: "Court Order / Judgment",
  LEGAL_NOTICE: "Legal Notice",
  SELLER_AFFIDAVIT: "Seller Affidavit",
  BANK_MORTGAGE_DOCUMENT: "Bank Loan / Mortgage Document",
  LOAN_CLOSURE_NOC: "Loan Closure / No-Dues Certificate",
  RELEASE_DEED: "Release Deed",
  BANK_NOC: "Bank NOC",
  BUILDING_PLAN: "Approved Building Plan",
  BUILDING_PLAN_APPROVAL: "Building Plan Approval",
  COMMENCEMENT_CERTIFICATE: "Commencement Certificate",
  OCCUPANCY_COMPLETION_CERTIFICATE: "Occupancy / Completion Certificate",
  LAND_CONVERSION_DOCUMENT: "Land Conversion / Land Use Document",
  SURVEY_SKETCH: "Survey Sketch",
  PROPERTY_TAX_RECEIPT: "Property Tax Receipt",
  SITE_LAYOUT_PLAN: "Approved Site / Layout Plan",
  OTHER: "Other document",
};
